# This is a SecretProviderClass example using service principal to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akvprovider-bunnyai
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: kv-bunnyai
    cloudName:                           # Defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: ROBOFLOW-API-KEY
          objectType: secret             # object types: secret, key or cert
          objectVersion: ""              # [OPTIONAL] object versions, default to latest if empty
    tenantId: "ee0ab6a5-6acc-4245-be1e-763c63ccbf12"                # The tenant ID of the Azure Key Vault instance